[2024-10-04T22:41:52.280+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_in_postgres.create_table_task manual__2024-10-04T22:41:45.234322+00:00 [queued]>
[2024-10-04T22:41:52.295+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_in_postgres.create_table_task manual__2024-10-04T22:41:45.234322+00:00 [queued]>
[2024-10-04T22:41:52.296+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-10-04T22:41:52.326+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_table_task> on 2024-10-04 22:41:45.234322+00:00
[2024-10-04T22:41:52.342+0000] {standard_task_runner.py:60} INFO - Started process 95 to run task
[2024-10-04T22:41:52.349+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_table_in_postgres', 'create_table_task', 'manual__2024-10-04T22:41:45.234322+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/create_mysql_table.py', '--cfg-path', '/tmp/tmp8yfuo02t']
[2024-10-04T22:41:52.354+0000] {standard_task_runner.py:88} INFO - Job 121: Subtask create_table_task
[2024-10-04T22:41:52.571+0000] {task_command.py:423} INFO - Running <TaskInstance: create_table_in_postgres.create_table_task manual__2024-10-04T22:41:45.234322+00:00 [running]> on host 005b6f55f237
[2024-10-04T22:41:52.736+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table_in_postgres' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T22:41:45.234322+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T22:41:45.234322+00:00'
[2024-10-04T22:41:52.739+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS clients (
            id SERIAL PRIMARY KEY,
            nom VARCHAR(100) NOT NULL,
            email VARCHAR(100) UNIQUE NOT NULL
        );
        
[2024-10-04T22:41:52.758+0000] {base.py:83} INFO - Using connection ID 'postgres_conn_id' for task execution.
[2024-10-04T22:41:52.791+0000] {base.py:83} INFO - Using connection ID 'postgres_conn_id' for task execution.
[2024-10-04T22:41:52.799+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.3), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2024-10-04T22:41:52.813+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=create_table_in_postgres, task_id=create_table_task, execution_date=20241004T224145, start_date=20241004T224152, end_date=20241004T224152
[2024-10-04T22:41:52.841+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 121 for task create_table_task (connection to server at "postgres" (172.18.0.3), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 95)
[2024-10-04T22:41:52.884+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-04T22:41:52.905+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
