[2024-10-04T22:01:58.673+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_in_mysql.create_table_task manual__2024-10-04T22:01:40.757714+00:00 [queued]>
[2024-10-04T22:01:58.690+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_in_mysql.create_table_task manual__2024-10-04T22:01:40.757714+00:00 [queued]>
[2024-10-04T22:01:58.691+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-10-04T22:01:58.715+0000] {taskinstance.py:2191} INFO - Executing <Task(MySqlOperator): create_table_task> on 2024-10-04 22:01:40.757714+00:00
[2024-10-04T22:01:58.737+0000] {standard_task_runner.py:60} INFO - Started process 89 to run task
[2024-10-04T22:01:58.740+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_table_in_mysql', 'create_table_task', 'manual__2024-10-04T22:01:40.757714+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/create_mysql_table.py', '--cfg-path', '/tmp/tmpxwqltzmn']
[2024-10-04T22:01:58.743+0000] {standard_task_runner.py:88} INFO - Job 73: Subtask create_table_task
[2024-10-04T22:01:58.816+0000] {task_command.py:423} INFO - Running <TaskInstance: create_table_in_mysql.create_table_task manual__2024-10-04T22:01:40.757714+00:00 [running]> on host e8b05ac5a569
[2024-10-04T22:01:58.938+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table_in_mysql' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T22:01:40.757714+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T22:01:40.757714+00:00'
[2024-10-04T22:01:58.940+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS clients (
            id INT AUTO_INCREMENT PRIMARY KEY,
            nom VARCHAR(100) NOT NULL,
            email VARCHAR(100) UNIQUE NOT NULL
        );
        
[2024-10-04T22:01:58.957+0000] {base.py:83} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2024-10-04T22:01:58.973+0000] {base.py:83} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2024-10-04T22:01:58.982+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/mysql/hooks/mysql.py", line 195, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 193, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)")
[2024-10-04T22:01:58.995+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=create_table_in_mysql, task_id=create_table_task, execution_date=20241004T220140, start_date=20241004T220158, end_date=20241004T220158
[2024-10-04T22:01:59.011+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 73 for task create_table_task ((2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)"); 89)
[2024-10-04T22:01:59.034+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-04T22:01:59.060+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
