[2024-10-05T01:41:32.052+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_employee_feedback_summary.insert_employee_feedback_data manual__2024-10-05T01:41:12.216410+00:00 [queued]>
[2024-10-05T01:41:32.069+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_employee_feedback_summary.insert_employee_feedback_data manual__2024-10-05T01:41:12.216410+00:00 [queued]>
[2024-10-05T01:41:32.071+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-10-05T01:41:32.096+0000] {taskinstance.py:2191} INFO - Executing <Task(MySqlOperator): insert_employee_feedback_data> on 2024-10-05 01:41:12.216410+00:00
[2024-10-05T01:41:32.109+0000] {standard_task_runner.py:60} INFO - Started process 133 to run task
[2024-10-05T01:41:32.115+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_employee_feedback_summary', 'insert_employee_feedback_data', 'manual__2024-10-05T01:41:12.216410+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/feedback.py', '--cfg-path', '/tmp/tmpzpobqcnb']
[2024-10-05T01:41:32.122+0000] {standard_task_runner.py:88} INFO - Job 140: Subtask insert_employee_feedback_data
[2024-10-05T01:41:32.282+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_employee_feedback_summary.insert_employee_feedback_data manual__2024-10-05T01:41:12.216410+00:00 [running]> on host ffa59a91c4ec
[2024-10-05T01:41:33.038+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='insert_employee_feedback_summary' AIRFLOW_CTX_TASK_ID='insert_employee_feedback_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T01:41:12.216410+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-05T01:41:12.216410+00:00'
[2024-10-05T01:41:33.052+0000] {sql.py:276} INFO - Executing: 
        INSERT INTO employee_feedback_summary (employee_name, department_name, feedback_rating)
        SELECT 
            e.name AS employee_name, 
            d.name AS department_name, 
            f.rating AS feedback_rating
        FROM 
            employees e
        JOIN 
            departments d ON e.department_id = d.id
        LEFT JOIN 
            feedback f ON e.id = f.employee_id;
        
[2024-10-05T01:41:33.081+0000] {base.py:83} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2024-10-05T01:41:33.103+0000] {base.py:83} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2024-10-05T01:41:33.143+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO employee_feedback_summary (employee_name, department_name, feedback_rating)
        SELECT 
            e.name AS employee_name, 
            d.name AS department_name, 
            f.rating AS feedback_rating
        FROM 
            employees e
        JOIN 
            departments d ON e.department_id = d.id
        LEFT JOIN 
            feedback f ON e.id = f.employee_id;
        , parameters: None
[2024-10-05T01:41:33.157+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'test_***.employees' doesn't exist")
[2024-10-05T01:41:33.175+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=insert_employee_feedback_summary, task_id=insert_employee_feedback_data, execution_date=20241005T014112, start_date=20241005T014132, end_date=20241005T014133
[2024-10-05T01:41:33.197+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 140 for task insert_employee_feedback_data ((1146, "Table 'test_***.employees' doesn't exist"); 133)
[2024-10-05T01:41:33.255+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-05T01:41:33.289+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
