[2024-10-04T22:35:05.287+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_in_postgres.create_table_task scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-10-04T22:35:05.308+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_in_postgres.create_table_task scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-10-04T22:35:05.310+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-10-04T22:35:05.341+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_table_task> on 2024-10-04 00:00:00+00:00
[2024-10-04T22:35:05.361+0000] {standard_task_runner.py:60} INFO - Started process 606 to run task
[2024-10-04T22:35:05.365+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_table_in_postgres', 'create_table_task', 'scheduled__2024-10-04T00:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/create_mysql_table.py', '--cfg-path', '/tmp/tmpsrh0ufj7']
[2024-10-04T22:35:05.369+0000] {standard_task_runner.py:88} INFO - Job 82: Subtask create_table_task
[2024-10-04T22:35:05.434+0000] {task_command.py:423} INFO - Running <TaskInstance: create_table_in_postgres.create_table_task scheduled__2024-10-04T00:00:00+00:00 [running]> on host e8b05ac5a569
[2024-10-04T22:35:05.536+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table_in_postgres' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T00:00:00+00:00'
[2024-10-04T22:35:05.538+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS clients (
            id SERIAL PRIMARY KEY,
            nom VARCHAR(100) NOT NULL,
            email VARCHAR(100) UNIQUE NOT NULL
        );
        
[2024-10-04T22:35:05.550+0000] {base.py:83} INFO - Using connection ID 'postgres_conn_id' for task execution.
[2024-10-04T22:35:05.563+0000] {base.py:83} INFO - Using connection ID 'postgres_conn_id' for task execution.
[2024-10-04T22:35:05.570+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-10-04T22:35:05.584+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=create_table_in_postgres, task_id=create_table_task, execution_date=20241004T000000, start_date=20241004T223505, end_date=20241004T223505
[2024-10-04T22:35:05.603+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 82 for task create_table_task (connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 606)
[2024-10-04T22:35:05.658+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-04T22:35:05.680+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
